# Generated by Django 4.1.7 on 2024-05-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="sports",
            field=models.CharField(
                default="", max_length=100, verbose_name="Student sports"
            ),
            preserve_default=False,
        ),
    ]
