# Generated by Django 4.1.7 on 2024-05-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0002_student_sports"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="Phone_No",
            field=models.IntegerField(
                default="", max_length=30, verbose_name="Student phone_No"
            ),
            preserve_default=False,
        ),
    ]
